### PR TITLE
Support an alt operation: (<|>)

### PR DESCRIPTION
**Pull request by LiamGoodacre**
I'm not massively familiar with transformers, so there may be a nicer way to write this?

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
(For https://github.com/hdgarrood/aeson-better-errors/issues/10)

**Comment by hdgarrood** [comment]
It might be easier to write this using `catchError` from the `MonadError` instance?

**Comment by LiamGoodacre** [comment]
Much better :)

**Comment by hdgarrood** [comment]
Looks great, thanks :) do you have a specific use case in mind for this, by the way?

**Comment by LiamGoodacre** [comment]
I was changing some stuff in psc `Docs.Types` and thought I needed this.  However I don't think I do now 😄as I've changed what I'm doing slightly.

**Pull request merged**
